In [1]:
from pathlib import Path
import sys

sys.path.append(str(Path.cwd().parent))

from rpp_dock.data.datamodule import DataModule

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
dm = DataModule(
    pdbdir='../structures/',
    train_csv='../splits_test.csv',
    val_csv='../splits_test.csv',
    batch_size=4
)
dm.setup("fit")

c:\Users\Пуся\Desktop\spbu\mcs_prac\mcs_prac\rpp_dock\utils\geom_utils.py:15: UserWarning: Using torch.cross without specifying the dim arg is deprecated.
Please either pass the dim explicitly or simply use torch.linalg.cross.
The default value of dim will change to agree with that of linalg.cross in a future release. (Triggered internally at ..\aten\src\ATen\native\Cross.cpp:67.)
  n_i = torch.cross(u_i, t_i) / torch.linalg.norm(torch.cross(u_i, t_i))


tensor([[  1,   2,  51,  ..., 126, 131, 190],
        [  0,   0,   0,  ..., 195, 195, 195]])


100%|██████████| 2252/2252 [00:03<00:00, 577.88it/s] 


tensor([[  1,   4,   5,  ...,  94,  91, 242],
        [  0,   0,   0,  ..., 247, 247, 247]])


100%|██████████| 2872/2872 [00:02<00:00, 1001.80it/s]


finish of apply_noise
tensor([[  1,   2,  51,  ..., 126, 131, 190],
        [  0,   0,   0,  ..., 195, 195, 195]])


100%|██████████| 2252/2252 [00:02<00:00, 867.83it/s]


tensor([[  1,   4,   5,  ...,  94,  91, 242],
        [  0,   0,   0,  ..., 247, 247, 247]])


100%|██████████| 2872/2872 [00:04<00:00, 683.75it/s]

finish of apply_noise


In [4]:
loader = dm.train_dataloader()
loader

In [5]:
batch = next(iter(loader))

In [6]:
# checking the coordinates after the noise for equality
for receptors, noised_ligands in loader: 
    assert not any(sum(noised_ligands[0].pos == noised_ligands[1].pos))


In [12]:
from biotite import structure
import numpy as np

ligand_0_fit, transformation = structure.superimpose(np.array(noised_ligands[0].true_pos), np.array(noised_ligands[0].pos))


In [18]:
ligand_1 = noised_ligands[1].pos
ligand_0 = noised_ligands[0].pos
assert not (transformation.apply(np.array(ligand_1)) == ligand_0)